metadata.format.version = "1.1"

[versions]

adventure = "5.2.0"
cloudburstnbt = "3.0.4.Final"
slf4j = "2.0.9"
math = "2.0"
fastutil-maps = "8.5.3"
netty = "4.2.1.Final"
gson = "2.11.0"
minecraftauth = "5.0.0"
checkerframework = "3.42.0"
junit = "5.14.4"

# buildSrc
indra = "4.1.0"
lombok-version = "1.18.42"
lombok-plugin = "9.5.0"

# gametest
loom = "1.17.19"
minecraft = "26.2"
fabric-loader = "0.19.3"
fabric-api = "0.156.0+26.2"

[libraries]

adventure-text-serializer-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }

cloudburstnbt = { module = "org.cloudburstmc:nbt", version.ref = "cloudburstnbt" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

math-api = { module = "org.cloudburstmc.math:api", version.ref = "math" }
math-immutable = { module = "org.cloudburstmc.math:immutable", version.ref = "math" }

fastutil-object2int-maps = { module = "com.nukkitx.fastutil:fastutil-object-int-maps", version.ref = "fastutil-maps" }
fastutil-int2object-maps = { module = "com.nukkitx.fastutil:fastutil-int-object-maps", version.ref = "fastutil-maps" }
fastutil-int2int-maps = { module = "com.nukkitx.fastutil:fastutil-int-int-maps", version.ref = "fastutil-maps" }

netty-all = { module = "io.netty:netty-all", version.ref = "netty" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

minecraftauth = { module = "net.raphimc:MinecraftAuth", version.ref = "minecraftauth" }

checkerframework-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerframework" }

# gametest
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

# buildSrc
indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
indra-git = { module = "net.kyori:indra-git", version.ref = "indra" }
lombok = { module = "io.freefair.gradle:lombok-plugin", version.ref = "lombok-plugin" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }

[bundles]

math = ["math-api", "math-immutable"]
fastutil = ["fastutil-object2int-maps", "fastutil-int2object-maps", "fastutil-int2int-maps"]
