name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # See https://github.com/actions/checkout/commits
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Set up JDK 1.8
        # See https://github.com/actions/setup-java/commits
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0
        with:
          java-version: 8
          distribution: temurin

      - name: Build with Maven
        run: mvn package -B
